### PR TITLE
support chinese encoding

### PR DESCRIPTION
**Pull request by janestar**
In this commit,I make the project support chinese encoding,Fix up the problem that can not read the file name or file path which contains chinese charactor .

### CODE REVIEW

**Comment by vpoughon** [comment]
Hello janestar and thank you for your contribution.

I just tried reading a file called 你好.tif on my system (Linux CentOS 7) and it works fine. UTF-8 supports Chinese encoding. I suspect the problem you are seeing is windows specific (or maybe a configuration issue).

We don't accept github PR, but could you please clarify what problem or error you are seeing when opening your file with Chinese characters? What happens on your system? Please open a bug report with details here: https://bugs.orfeo-toolbox.org

Thanks.

**Comment by janestar** [comment]
Hello vpoughon, I use the binaries (OTB-5.8.0-win32) on my system(Windows 10). I tried reading a file 你好.tif ,then the message box alert that "Could not create IO object for file ......" ,So I complied the source code, found that this may be caused by GDAL,So I add this line "CPLSetConfigOption("GDAL_FILENAME_IS_UTF8","NO");" to make the program work on Windows10.

**Comment by vpoughon** [comment]
ok thanks. I just reproduced the bug on my windows machine.
I opened a ticket here: https://bugs.orfeo-toolbox.org/view.php?id=1318

**Comment by vpoughon** [comment]
@janestar  I tried your patch on Windows and it doesn't fix the problem for me. Were you able to open your image with it?
(You can find a windows build with the patch here: https://www.orfeo-toolbox.org/packages/nightly/latest/)

**Pull request closed without merging**
