### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/orfeotoolbox/OTB/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/orfeotoolbox/OTB).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by vpoughon** [comment]
Thanks, the alerts look interesting. Note if you want to contribute to OTB directly you will need to sign a CLA first as explained in our [CONTRIBUTING.md](https://github.com/orfeotoolbox/OTB/blob/develop/CONTRIBUTING.md#contribution-license-agreement).

**Comment by xcorail** [comment]
Hello @vpoughon 

Happy the alerts are interesting to you. The usage I recommend is to integrate our analyses in your Pull requests. LGTM will then report new problems (or fixes) directly within the PR. It's a [one-click operation](https://lgtm.com/projects/g/orfeotoolbox/OTB/ci/)

If you are interested also in the code quality badges, let me know, and I'll sign the CLA.

**Comment by sjvs** [comment]
Hi @vpoughon! LGTM.com is a free service for repositories that are hosted on GitHub.com and Bitbucket.org (soon also GitLab.org!). APIs for interacting with LGTM are under development, but these will only work for code hosted on GitHub.com and Bitbucket.org. So you could use those APIs to interact with the LGTM analysis on your GitHub mirror, but not on your self-hosted GitLab instance.

Alternatively, LGTM comes in an enterprise (on-premise) variant, but I doubt whether that is what you're looking for.

**Comment by vpoughon** [comment]
ok interesting product you have, thanks!

**Pull request closed without merging**
